str = ''
str += '<div id="footer">'
str += '	<div class="inner">'
str += '		<div class="logo ico"><span class="blind">SK Plasma</span></div>'
str += '		<p class="address">경기도 성남시 분당구 판교로 310 [13494] TEL) 02-2008-2008 <br>Copyright(c) SK Plasma. All Right Reserved.</p>'
str += '		<ul class="add">'
str += '			<li><a href="FO-01.html">개인정보취급방침</a></li>'
str += '			<li><a href="https://ethics.sk.co.kr/Kor/Main.aspx" target="_blank">SK윤리경영 상담∙제보</a><span class="bar"></span></li>'
str += '		</ul>'
str += ''
str += '		<a href="javascript:" class="inquiry">문의하기</a>'
str += ''
str += '		<div class="family">'
str += '			<a href="#none" class="f_btn">패밀리 사이트</a>'
str += '			<ul class="lst_site">'
str += '				<li><a href="#none" title="SK주식회사 홈페이지 바로가기(새창)">SK주식회사</a></li>'
str += '				<li><a href="#none" title="SK디스커버리 홈페이지 바로가기(새창)">SK디스커버리</a></li>'
str += '				<li><a href="#none" title="SK케미칼 홈페이지 바로가기(새창)">SK케미칼</a></li>'
str += '				<li><a href="#none" title="SK바이오사이언스 홈페이지 바로가기(새창)">SK바이오사이언스</a></li>'
str += '			</ul>'
str += '			<a href="#none" class="submit">이동</a>'
str += '		</div>'
str += '	</div>'
str += '</div>'

document.write(str);