str = ''
str += '<div id="header">'

if ($('body').hasClass("home") || $('body').hasClass("page")) {
	str += '<div class="h_group">'
} else {
	str += '<div class="h_group privacy">'
}

str += '		<div>'
str += '			<h1>'
str += '				<a href="index.html" class="logo">'
str += '					<span class="blind">SK plasma</span>'
str += '				</a>'
str += '			</h1>'
str += ''
str += '			<div id="gnb">'
str += '				<a href="javascript:" class="btn_menu">'
str += '					<span><i>전체메뉴 열기</i></span>'
str += '				</a>'
str += '				<div class="box">'
str += '					<button type="button" class="btn_close">전체메뉴 닫기</button>'
str += '					<ul>'
str += '						<li><a href="CO-01.html">회사소개</a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="CO-01.html">CEO 인사말</a></li>'
str += '									<li><a href="CO-02.html">회사개요</a></li>'
str += '									<li><a href="CO-03.html">회사연혁</a></li>'
str += '									<li><a href="CO-04.html">기업문화</a></li>'
str += '									<li><a href="CO-05.html">관계사</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="BU-01.html">사업소개</a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="BU-01.html">혈액제제 소개</a></li>'
str += '									<li><a href="BU-02.html">제품정보</a></li>'
str += '									<li><a href="BU-03.html">Global Business</a></li>'
str += '									<li><a href="BU-04.html">연구개발</a></li>'
str += '									<li><a href="BU-05.html">제품소식</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="RE-01.html">인재채용</a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="RE-01.html">SKP 사람들</a></li>'
str += '									<li><a href="RE-02.html">SKP 미리보기</a></li>'
str += '									<li><a href="RE-03.html">사내문화/복지</a></li>'
str += '									<li><a href="RE-04.html">직무소개</a></li>'
str += '									<li><a href="RE-05.html">지원하기</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="CS-01.html">CSV</a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="CS-01.html">사회적가치</a></li>'
str += '									<li><a href="CS-02.html">사회공헌</a></li>'
str += '									<li><a href="CS-03.html">윤리경영</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="CR-01.html">고객지원</a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="CR-01.html">공지사항</a></li>'
str += '									<li><a href="CR-02.html">문의안내</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '					</ul>'
str += '				</div>'
str += '			</div>'
str += ''
str += '			<div class="util_menu">'
str += '				<a href="javascript:">문의하기</a>'
str += '				<a href="javascript:" class="_global" title="한국어">한국어</a>'
str += '				<a href="javascript:" class="_global" title="ENG">ENG</a>'
str += '				<ul class="list_global mobile">'
str += '					<li class="on"><a href="javascript:" title="SK plasma 국문 홈페이지">KOR</a></li>'
str += '					<li><a href="javascript:" target="_blank" title="SK plasma 영문 홈페이지">ENG</a></li>'
str += '				</ul>'
str += '			</div>'
str += '		</div>'
str += ''
str += '	</div>'
str += '</div>'

document.write(str);